from __future__ import annotations

from enum import Enum


class ReasonId(str, Enum):
    # --- Presence / shape checks ---
    TVA_MISSING_CONTEXT = "TVA_MISSING_CONTEXT"
    TVA_MISSING_VERDICT = "TVA_MISSING_VERDICT"
    TVA_MISSING_AUTHORITY = "TVA_MISSING_AUTHORITY"

    # --- Verdict checks ---
    TVA_VERDICT_NOT_ALLOW = "TVA_VERDICT_NOT_ALLOW"

    # --- Binding checks (authority must match the context) ---
    TVA_AUTHORITY_WALLET_MISMATCH = "TVA_AUTHORITY_WALLET_MISMATCH"
    TVA_AUTHORITY_ACTION_MISMATCH = "TVA_AUTHORITY_ACTION_MISMATCH"
    TVA_AUTHORITY_CONTEXT_HASH_MISMATCH = "TVA_AUTHORITY_CONTEXT_HASH_MISMATCH"

    # --- Time checks (deterministic: `now` is injected) ---
    TVA_MISSING_NOW = "TVA_MISSING_NOW"
    TVA_INVALID_TIME_WINDOW = "TVA_INVALID_TIME_WINDOW"
    TVA_AUTHORITY_NOT_YET_VALID = "TVA_AUTHORITY_NOT_YET_VALID"
    TVA_AUTHORITY_EXPIRED = "TVA_AUTHORITY_EXPIRED"

    # --- Nonce / replay checks (store is injected) ---
    TVA_MISSING_NONCE_STORE = "TVA_MISSING_NONCE_STORE"
    TVA_NONCE_REPLAY = "TVA_NONCE_REPLAY"
    TVA_INVALID_NONCE = "TVA_INVALID_NONCE"

    # --- EQC (Decision) basic validation ---
    EQC_MISSING_WALLET_ID = "EQC_MISSING_WALLET_ID"
    EQC_MISSING_ACTION = "EQC_MISSING_ACTION"

    # --- EQC (Decision) integration evidence (fail-closed) ---
    EQC_MISSING_NOW = "EQC_MISSING_NOW"
    EQC_MISSING_QID_SESSION = "EQC_MISSING_QID_SESSION"
    EQC_QID_SESSION_EXPIRED = "EQC_QID_SESSION_EXPIRED"
    EQC_QID_SESSION_NOT_YET_VALID = "EQC_QID_SESSION_NOT_YET_VALID"
    EQC_INVALID_QID_PROOF = "EQC_INVALID_QID_PROOF"

    EQC_MISSING_RISK_REPORT = "EQC_MISSING_RISK_REPORT"
    EQC_RISK_CONTEXT_HASH_MISMATCH = "EQC_RISK_CONTEXT_HASH_MISMATCH"
    EQC_RISK_SCORE_BELOW_THRESHOLD = "EQC_RISK_SCORE_BELOW_THRESHOLD"
    EQC_INVALID_RISK_REPORT = "EQC_INVALID_RISK_REPORT"

    # --- External reason mapping (adapter boundary) ---
    UNKNOWN_EXTERNAL_REASON = "UNKNOWN_EXTERNAL_REASON"

        # --- Evidence / signal normalization ---
    EVIDENCE_OK = "EVIDENCE_OK"
    
    # --- WSQK (Authority issuer) validation ---
    WSQK_MISSING_WALLET_ID = "WSQK_MISSING_WALLET_ID"
    WSQK_MISSING_ACTION = "WSQK_MISSING_ACTION"
    WSQK_MISSING_CONTEXT_HASH = "WSQK_MISSING_CONTEXT_HASH"
    WSQK_MISSING_NOW = "WSQK_MISSING_NOW"
    WSQK_INVALID_TTL = "WSQK_INVALID_TTL"
    WSQK_INVALID_NONCE = "WSQK_INVALID_NONCE"
