from __future__ import annotations

from enum import Enum


class ReasonId(str, Enum):
    # --- Presence / shape checks ---
    TVA_MISSING_CONTEXT = "TVA_MISSING_CONTEXT"
    TVA_MISSING_VERDICT = "TVA_MISSING_VERDICT"
    TVA_MISSING_AUTHORITY = "TVA_MISSING_AUTHORITY"

    # --- Verdict checks ---
    TVA_VERDICT_NOT_ALLOW = "TVA_VERDICT_NOT_ALLOW"

    # --- Binding checks (authority must match the context) ---
    TVA_AUTHORITY_WALLET_MISMATCH = "TVA_AUTHORITY_WALLET_MISMATCH"
    TVA_AUTHORITY_ACTION_MISMATCH = "TVA_AUTHORITY_ACTION_MISMATCH"
    TVA_AUTHORITY_CONTEXT_HASH_MISMATCH = "TVA_AUTHORITY_CONTEXT_HASH_MISMATCH"

    # --- Time checks (deterministic: `now` is injected) ---
    TVA_MISSING_NOW = "TVA_MISSING_NOW"
    TVA_INVALID_TIME_WINDOW = "TVA_INVALID_TIME_WINDOW"
    TVA_AUTHORITY_NOT_YET_VALID = "TVA_AUTHORITY_NOT_YET_VALID"
    TVA_AUTHORITY_EXPIRED = "TVA_AUTHORITY_EXPIRED"

    # --- Nonce / replay checks (store is injected) ---
    TVA_MISSING_NONCE_STORE = "TVA_MISSING_NONCE_STORE"
    TVA_NONCE_REPLAY = "TVA_NONCE_REPLAY"
    TVA_INVALID_NONCE = "TVA_INVALID_NONCE"

    # --- WSQK v2 TVA quantum-aware enforcement ---
    TVA_WSQK_V2_REQUIRED = "TVA_WSQK_V2_REQUIRED"
    TVA_WSQK_V2_EVIDENCE_FAMILY_MISMATCH = "TVA_WSQK_V2_EVIDENCE_FAMILY_MISMATCH"
    TVA_WSQK_V2_QUANTUM_POSTURE_MISMATCH = "TVA_WSQK_V2_QUANTUM_POSTURE_MISMATCH"
    TVA_WSQK_V2_PROOF_BINDINGS_HASH_MISMATCH = "TVA_WSQK_V2_PROOF_BINDINGS_HASH_MISMATCH"

    # --- EQC (Decision) basic validation ---
    EQC_MISSING_WALLET_ID = "EQC_MISSING_WALLET_ID"
    EQC_MISSING_ACTION = "EQC_MISSING_ACTION"

    # --- EQC (Decision) integration evidence (fail-closed) ---
    EQC_MISSING_NOW = "EQC_MISSING_NOW"
    EQC_MISSING_QID_SESSION = "EQC_MISSING_QID_SESSION"
    EQC_QID_SESSION_EXPIRED = "EQC_QID_SESSION_EXPIRED"
    EQC_QID_SESSION_NOT_YET_VALID = "EQC_QID_SESSION_NOT_YET_VALID"
    EQC_INVALID_QID_PROOF = "EQC_INVALID_QID_PROOF"
    EQC_QID_CONTEXT_HASH_MISMATCH = "EQC_QID_CONTEXT_HASH_MISMATCH"

    # --- Q-ID linkage hardening (v1.4.0) ---
    QID_REPLAY_PROOF_MISSING = "QID_REPLAY_PROOF_MISSING"
    QID_REPLAY_PROOF_INVALID = "QID_REPLAY_PROOF_INVALID"
    QID_REPLAY_WALLET_MISMATCH = "QID_REPLAY_WALLET_MISMATCH"
    QID_REPLAY_SUBJECT_MISMATCH = "QID_REPLAY_SUBJECT_MISMATCH"
    QID_REPLAY_DEVICE_MISMATCH = "QID_REPLAY_DEVICE_MISMATCH"
    QID_REPLAY_PROOF_HASH_MISMATCH = "QID_REPLAY_PROOF_HASH_MISMATCH"
    QID_REPLAY_NONCE_MISMATCH = "QID_REPLAY_NONCE_MISMATCH"
    QID_NONCE_REPLAY = "QID_NONCE_REPLAY"

    EQC_MISSING_RISK_REPORT = "EQC_MISSING_RISK_REPORT"
    EQC_RISK_CONTEXT_HASH_MISMATCH = "EQC_RISK_CONTEXT_HASH_MISMATCH"
    EQC_RISK_SCORE_BELOW_THRESHOLD = "EQC_RISK_SCORE_BELOW_THRESHOLD"
    EQC_INVALID_RISK_REPORT = "EQC_INVALID_RISK_REPORT"

    # --- EQC (v2 multi-evidence) additions ---
    EQC_MISSING_ORACLE = "EQC_MISSING_ORACLE"
    EQC_MISSING_SHIELD_BUNDLE = "EQC_MISSING_SHIELD_BUNDLE"
    EQC_INVALID_SHIELD_BUNDLE = "EQC_INVALID_SHIELD_BUNDLE"
    EQC_SHIELD_CONTEXT_HASH_MISMATCH = "EQC_SHIELD_CONTEXT_HASH_MISMATCH"
    EQC_SHIELD_STALE = "EQC_SHIELD_STALE"
    EQC_CONFLICTING_EVIDENCE = "EQC_CONFLICTING_EVIDENCE"

    # --- External reason mapping (adapter boundary) ---
    UNKNOWN_EXTERNAL_REASON = "UNKNOWN_EXTERNAL_REASON"

    # --- Evidence / signal normalization ---
    EVIDENCE_OK = "EVIDENCE_OK"

    # --- WSQK (Authority issuer) validation ---
    WSQK_MISSING_WALLET_ID = "WSQK_MISSING_WALLET_ID"
    WSQK_MISSING_ACTION = "WSQK_MISSING_ACTION"
    WSQK_MISSING_CONTEXT_HASH = "WSQK_MISSING_CONTEXT_HASH"
    WSQK_MISSING_NOW = "WSQK_MISSING_NOW"
    WSQK_INVALID_TTL = "WSQK_INVALID_TTL"
    WSQK_INVALID_NONCE = "WSQK_INVALID_NONCE"

    # --- WSQK v2 quantum-aware authority validation ---
    WSQK_V2_INVALID_EVIDENCE_FAMILIES = "WSQK_V2_INVALID_EVIDENCE_FAMILIES"
    WSQK_V2_UNKNOWN_EVIDENCE_FAMILY = "WSQK_V2_UNKNOWN_EVIDENCE_FAMILY"
    WSQK_V2_INVALID_QUANTUM_POSTURE = "WSQK_V2_INVALID_QUANTUM_POSTURE"
    WSQK_V2_AUTHORITY_MAPPING_MISSING_FIELD = "WSQK_V2_AUTHORITY_MAPPING_MISSING_FIELD"
    WSQK_V2_AUTHORITY_MAPPING_INVALID_FIELD = "WSQK_V2_AUTHORITY_MAPPING_INVALID_FIELD"


    # --- WSQK v2 <-> Q-ID hybrid posture binding ---
    WSQK_QID_POSTURE_MISMATCH = "WSQK_QID_POSTURE_MISMATCH"
    WSQK_QID_HYBRID_REQUIRED = "WSQK_QID_HYBRID_REQUIRED"
    WSQK_QID_BINDING_INVALID = "WSQK_QID_BINDING_INVALID"

    # --- Execution Envelope v1 (request/response contracts) ---
    OK_ALLOW = "OK_ALLOW"

    DENY_SCHEMA_INVALID = "DENY_SCHEMA_INVALID"
    DENY_UNKNOWN_FIELD = "DENY_UNKNOWN_FIELD"
    DENY_VERSION_MISMATCH = "DENY_VERSION_MISMATCH"
    DENY_INTENT_UNSUPPORTED = "DENY_INTENT_UNSUPPORTED"
    DENY_PAYLOAD_INVALID = "DENY_PAYLOAD_INVALID"

    DENY_TIMEBOX_INVALID = "DENY_TIMEBOX_INVALID"
    DENY_TIMEBOX_EXPIRED = "DENY_TIMEBOX_EXPIRED"
    DENY_TIMEBOX_NOT_YET_VALID = "DENY_TIMEBOX_NOT_YET_VALID"
    DENY_TIMEBOX_SKEW_EXCEEDED = "DENY_TIMEBOX_SKEW_EXCEEDED"

    DENY_NONCE_INVALID = "DENY_NONCE_INVALID"
    DENY_NONCE_REPLAY = "DENY_NONCE_REPLAY"
    DENY_NONCE_STORE_ERROR = "DENY_NONCE_STORE_ERROR"

    DENY_AUTHORITY_INVALID = "DENY_AUTHORITY_INVALID"
    DENY_AUTHORITY_INSUFFICIENT = "DENY_AUTHORITY_INSUFFICIENT"

    DENY_POLICY = "DENY_POLICY"
    DENY_EQC = "DENY_EQC"
    DENY_WSQK = "DENY_WSQK"
    DENY_TVA = "DENY_TVA"

    DENY_ADAPTER_INVALID = "DENY_ADAPTER_INVALID"
    DENY_ADAPTER_UNAVAILABLE = "DENY_ADAPTER_UNAVAILABLE"

    ERR_INTERNAL = "ERR_INTERNAL"
    ERR_UNHANDLED = "ERR_UNHANDLED"

    DENY_NOT_WIRED = "DENY_NOT_WIRED"
