from __future__ import annotations

from enum import Enum


class ReasonId(str, Enum):
    # --- Presence / shape checks ---
    TVA_MISSING_CONTEXT = "TVA_MISSING_CONTEXT"
    TVA_MISSING_VERDICT = "TVA_MISSING_VERDICT"
    TVA_MISSING_AUTHORITY = "TVA_MISSING_AUTHORITY"

    # --- Verdict checks ---
    TVA_VERDICT_NOT_ALLOW = "TVA_VERDICT_NOT_ALLOW"

    # --- Binding checks (authority must match the context) ---
    TVA_AUTHORITY_WALLET_MISMATCH = "TVA_AUTHORITY_WALLET_MISMATCH"
    TVA_AUTHORITY_ACTION_MISMATCH = "TVA_AUTHORITY_ACTION_MISMATCH"
    TVA_AUTHORITY_CONTEXT_HASH_MISMATCH = "TVA_AUTHORITY_CONTEXT_HASH_MISMATCH"

    # --- Time checks (deterministic: `now` is injected) ---
    TVA_MISSING_NOW = "TVA_MISSING_NOW"
    TVA_INVALID_TIME_WINDOW = "TVA_INVALID_TIME_WINDOW"
    TVA_AUTHORITY_NOT_YET_VALID = "TVA_AUTHORITY_NOT_YET_VALID"
    TVA_AUTHORITY_EXPIRED = "TVA_AUTHORITY_EXPIRED"

    # --- Nonce / replay checks (store is injected) ---
    TVA_MISSING_NONCE_STORE = "TVA_MISSING_NONCE_STORE"
    TVA_NONCE_REPLAY = "TVA_NONCE_REPLAY"
    TVA_INVALID_NONCE = "TVA_INVALID_NONCE"
